name: Nice Tuto
on:
  push:
    branches:
      - custom-actions
  pull_request:
    branches:
      - main
jobs:
  beautiful-job-push:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Job automatically triggered by a ${{ github.event_name }} event."
      - run: "Push on custom-actions"

